apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: hcrespo
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1 # Update the version of nginx from 1.14.2 to 1.16.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: hcrespo
  labels:
    app: nginx_service_label
spec:
  type: NodePort
  selector:
    app: nginx # this needs to match the pod label (template -> metadata -> labels -> app)
  ports:
  - name: http
    port: 8080 # port accesible inside the cluster - redirects the traffic to targetPort
    targetPort: 80 # this should match the containerPort
    nodePort: 30005 # use this port to access the server from outside - redirects the traffic to targetPort