apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: guestbook
    tier: frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  # https://stackoverflow.com/questions/60286558/kubernetes-load-balancer-external-ip-pending
  # LoadBalancer doesn't work on bare metal clusters, only in cloud providers. Use NodePort instead.
  # type: LoadBalancer
  type: NodePort
  selector:
    app: guestbook
    tier: frontend
  ports:
  - name: http
    port: 80 # the port that this service should serve on
    targetPort: 80
    nodePort: 30006