apiVersion: v1
kind: Service
metadata:
  name: redis-leader
  # this labels the previously defined in the deployment.yml, so the Service routes network traffic to the Redis Pod.
  labels:
    app: redis
    role: leader
    tier: backend
spec:
  # this services does not expose any public port
  type: ClusterIP # this is the default value
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    role: leader
    tier: backend