apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-depl # this is required
  namespace: hcrespo
  # labels:
    # app: apache-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache-label-1
  template:
    metadata:
      labels:
        app: apache-label-1
    spec:
      containers:
      - name: apache-container
        image: httpd:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80 # the port on which the app can be reached out inside the container
---
apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: hcrespo
  labels:
    app: apache_app_service_label
spec:
  type: NodePort
  selector:
    app: apache-label-1 # this needs to match the pod label (template -> metadata -> labels -> app)
  ports:
  - name: http
    port: 8080 # port accesible inside the cluster - redirects the traffic to targetPort
    targetPort: 80 # this should match the containerPort
    nodePort: 30004 # use this port to access the server from outside - redirects the traffic to targetPort
